name: CI — matrix

on:
  push:
    branches: [ "feature/tasks4", "main", "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tasks3/requirements.txt ]; then pip install -r tasks3/requirements.txt; fi

      - name: Run tests
        run: |
          python -m pytest -q tasks3/tests

      - name: Dashboard import smoke (non-interactive)
        run: |
          python - <<'PY'
import sys
from pathlib import Path
ROOT = Path('.').resolve()
SRC = ROOT / 'tasks3' / 'src'
sys.path.insert(0, str(SRC))
try:
    import tasks3_cli.dashboard as d
    print('dashboard-import-ok')
except Exception as e:
    print('dashboard-import-failed', e)
    raise
PY
